USE bookstore_db;

-- Insert Books into Book Table
INSERT INTO Author(firstName,lastName,createdAt,updatedAt) 
VALUES
('Elin','Hildebrand',sysdate(),sysdate())
,('Brit','Bennett',sysdate(),sysdate())
,('John','Bolton',sysdate(),sysdate())
,('Robin','DiAngelo',sysdate(),sysdate())
,('Delia','Owens',sysdate(),sysdate())
,('John','Grisham',sysdate(),sysdate())
,('Ibram X.','Kendi',sysdate(),sysdate())
,('Celeste','Ng',sysdate(),sysdate())
,('Ijeoma','Oluo',sysdate(),sysdate())
,('Harper','Lee',sysdate(),sysdate())
,('L.M.','Montgomery',sysdate(),sysdate())
,('Jack','London',sysdate(),sysdate())
,('Jane','Austen',sysdate(),sysdate())
,('F. Scott','Fitzgerald',sysdate(),sysdate())
,('Emily','Bronte',sysdate(),sysdate())
,('Oscar','Wilde',sysdate(),sysdate())
,('George','Orwell',sysdate(),sysdate())
,('J.D.','Salinger',sysdate(),sysdate())
,('Shel','Silverstein',sysdate(),sysdate())
,('Maurice','Sendak',sysdate(),sysdate())
,('Dr.','Suess',sysdate(),sysdate())
,('Beatrix','Potter',sysdate(),sysdate())
,('C.S.','Lewis',sysdate(),sysdate())
,('E.B.','White',sysdate(),sysdate())
,('Eric','Carle',sysdate(),sysdate())
,('Michael','Ende',sysdate(),sysdate())
,('Howard','Zinn',sysdate(),sysdate())
,('Norton','Juster',sysdate(),sysdate())
,('Kurt','Vonnegut',sysdate(),sysdate())
,('Chinua','Achebe',sysdate(),sysdate())
,('Kazuo','Ishiguro',sysdate(),sysdate())
,('Art','Spiegelman',sysdate(),sysdate())
,('Margaret','Atwood',sysdate(),sysdate())
,('Douglas','Adams',sysdate(),sysdate())
,('David Foster','Wallace',sysdate(),sysdate())
,('Philip D.','Morgan',sysdate(),sysdate())
,('Hortense','Spillers',sysdate(),sysdate())
,('Stephen','Best',sysdate(),sysdate())
,('Anthony B.','Pinn',sysdate(),sysdate())
,('Harvey','Young',sysdate(),sysdate())
,('Michael A.','Gomez',sysdate(),sysdate())
,('Sarah','Haley',sysdate(),sysdate())
,('Daryl Michael','Scott',sysdate(),sysdate())
,('Cheryl','Harris',sysdate(),sysdate())
,('Frank','Herbert',sysdate(),sysdate())
,('Andrzej','Sapkowski',sysdate(),sysdate())
,('J.R.R.','Tolkein',sysdate(),sysdate())
,('J.K.','Rowling',sysdate(),sysdate())
,('Stephenie','Meyer',sysdate(),sysdate())
,('George R. R.','Martin',sysdate(),sysdate())
,('Diana','Gabaldon',sysdate(),sysdate())
,('Robert','Jordan',sysdate(),sysdate())
,('Cixin','Liu',sysdate(),sysdate())